
export const posts = [
    {
        claimed: true,
        winner: 'https://opensea.io/edbailey',
        winner_name: 'edbailey',
        open_sea_url: 'https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/45467654088607569510196568564608339478309866350944487180964186461026683715585',
        question: '0.75 as a fraction',
        slug:'0.75-as-a-fraction',
        type_of_question: 'fraction',
        meta_description: "Convert 0.75 into a fraction with our simple step-by-step guide. Learn how to identify the place value and simplify the fraction for easy use. Earn a money reward if you can solve this question correctly!",
        page_thumbnail: 'gold-chest.webp',
        answer_tip: "",
        hints_intro: "",
        hint_1_title: "Convert the fraction with a denominator of 1:",
        hint_1: "Start by writing the decimal as a fraction with a denominator of 1. This helps you understand the relationship between the decimal and the whole number.",
        hint_2_title: "Identify the place value:",
        hint_2: "The next step is to identify the place value of the decimal. This will give you the denominator of the fraction.",
        hint_3_title: "Simplify the fraction:",
        hint_3: "Simplifying the fraction makes it easier to understand and use in other calculations. To simplify, divide both the numerator and denominator by their greatest common factor.",
        step_intro: "To solve 0.75 as a fraction, we need to understand how to convert decimals into fractions.",
        step_1: " Start by writing 0.75 as a fraction with a denominator of 1. So, 0.75 becomes 75/100.",
        step_2: "Next identify the place value. In this case, the decimal point is after the hundredth place. This means that the denominator of the fraction will be 100.",
        step_3: "Then multiply the decimal by the denominator: Multiply 0.75 by 100 to get the numerator of the fraction. So, 75/100 is your fraction. Lastly simplify this fraction by dividing by the greatest common factor to get the fraction in its simplist form."
    },

    {
        question: '0.125 as a fraction',
        slug:'0.125-as-a-fraction',
        type_of_question: 'fraction',
        meta_description: "0.125 as a fraction involves converting this decimal into a fraction in its simplest form. Earn a money reward if you can solve this question correctly!",
        page_thumbnail: "2.webp",
        answer_tip: "",
        hints_intro: "",
        hint_1_title: "Write down the decimal as a fraction with a denominator of 1:",
        hint_1: "Start by writing the decimal as a fraction with a denominator of 1. This helps you understand the relationship between the decimal and the whole number.",
        hint_2_title: "Identify the place value:",
        hint_2: "The next step is to identify the place value of the decimal. This will give you the denominator of the fraction.",
        hint_3_title: "Simplify the fraction:",
        hint_3: "Simplifying the fraction makes it easier to understand and use in other calculations. To simplify, divide both the numerator and denominator by their greatest common factor.",
        step_intro: "To solve 0.125 as a fraction, we need to understand how to convert decimals into fractions.",
        step_1: " The first step is to identify the place value of the decimal point. In this case, the decimal point is after the hundredths place.",
        step_2: "The next step is to write the decimal as a fraction. To do this, we will use the place value as the denominator of the fraction. In this case, the denominator is 100 because the decimal point is after the hundredths place. The numerator is the decimal's value multiplied by the denominator. In this case, it is 0.125 * 100 = 12.5",
        step_3: "The fraction 12.5/100 can be simplified. To simplify, divide both the numerator and the denominator by their greatest common factor. In this case, both 12.5 and 100 can be divided by 5."
    },

    {
        question: '3 fifteens',
        slug:'3-fifteens',
        type_of_question: 'multiplication',
        meta_description: "3 fifteens can also be written as a multiplication question as 3 x 15. Convert the words fifteens into numbers to answer. Earn a money reward if you can solve this question correctly!",
        page_thumbnail: "3.webp",
        answer_tip: "",
        hints_intro: "",
        hint_1_title: "Convert words to numbers:",
        hint_1: "To make the problem easier, convert fifteen into 15 so that you are working with two numbers.",
        hint_2_title: "Use visual aids:",
        hint_2: "Visual aids, like drawings or manipulatives, can help you understand and solve the problem. For example, you can draw three blocks and label each one with the number 15.",
        hint_3_title: "Use mental math:",
        hint_3: "Try to solve the problem mentally, without writing it down as this can help your mental math and speed up the process of solving multiplication problems.",
        step_intro: "To solve 3 fifteens, we need to understand what multiplication is and how to multiply numbers. Multiplication is simply a way of adding the same number multiple times.",
        step_1: "Convert fifteen into the number 15 to make it easier to solve the question.",
        step_2: "You can also think of adding 15 three times",
        step_3: "Now that we have both numbers, we can combine them to solve the problem. We're going to add 15 three times, so we write 3 x 15"
    },

    {
        question: '5 1/2 as a decimal',
        slug:'5-1:2-as-a-decimal',
        type_of_question: 'decimal',
        meta_description: "What is 5 1/2 as a decimal? Convert this fraction into a decimal and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "4.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to help solve this decimal question:",
        hint_1_title: "Break it down:",
        hint_1: "To make the problem easier, break it down into smaller parts. Think about what the mixed number 5 1/2 means, and what it represents.",
        hint_2_title: "Visual aids:",
        hint_2: "Visual aids, like drawings or manipulatives, can help you understand and solve the problem. For example, you can draw a circle or a rectangle to represent the fraction 1/2.",
        hint_3_title: "Use a calculator:",
        hint_3: "If you're having trouble converting from a fraction to a decimal, you can use a calculator. Try to use mental math first as this will improve your understanding and speed for solving these questions.",
        step_intro: "Converting a mixed number like 5 1/2 into a decimal can be done with a few simple steps.",
        step_1: "Write the fraction part of the mixed number as a fraction. In this case, the fraction part is 1/2. So, we write it as 1/2.",
        step_2: "Divide the numerator (the top number) by the denominator (the bottom number).To do this, we divide 1 by 2 and we get 0.5",
        step_3: "Next simply add that to your whole number (5) and you'll have your answer!"
    },

    {
        question: '5 is what percent of 2',
        slug:'5-is-what-percent-of-2',
        type_of_question: 'percent',
        meta_description: "5 is what percent of 2? Learn how to calculate 5 as a percent of 2 and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "2.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to help convert solve this percentage question:",
        hint_1_title: "First convert the percent to an equivalent fraction:",
        hint_1: "To convert a percent into a fraction, we need to convert to an equivalent fraction with denominator 100.",
        hint_2_title: "Convert fraction to a decimal:",
        hint_2: "Convert the fraction to a decimal first, then multiply the answer by 100",
        hint_3_title: "Use a calculator:",
        hint_3: "If you're having trouble dividing the numerator by the denominator, you can use a calculator to do it for you. Ideally use a calculate to check your answer as it is better to practice converting fractions to percentages and using a calculator to check your answer.",
        step_intro: "Percentage is a way of expressing a number as a part of 100. To find the percentage of a number, we first need to divide it by the total amount and then multiply by 100.",
        step_1: "First we need to convert our denominator 2 to 100 to represent 100% as a percent.",
        step_2: "Next we divide 100 by our denominator (2) to work out the multiplier. 100 divided by 2 is 50 which is our multiplier.",
        step_3: "Our last step is then to convert our numerator (5) using the same multipler (50) to get our percentage."
    },

    {
        question: '5 is what percent of 20',
        slug:'5-is-what-percent-of-20',
        type_of_question: 'percent',
        meta_description: "5 is what percent of 20? Use equivalent fractions to convert 5 to a percent of 20 and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "4.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to help convert 5 into 20 as a percent:",
        hint_1_title: "Use an equivalent fraction to convert the percent:",
        hint_1: "Find the multiple that converts the denominator into 100 and then multiply the numerator by that same multiple.",
        hint_2_title: "Use decimals:",
        hint_2: "Alternatively, you could convert the fraction into a decimal first and then multiply that decimal by 100 to get a percent.",
        hint_3_title: "Use a calculator:",
        hint_3: "As a last resort, use a calculator to do the conversion. Ideally you should use a calculator to check your workings as it is better to get the practice of doing the conversions yourself first.",
        step_intro: "A percentage is a way of representing a number as a part of 100. It is a way of standardizing fractions to make them easier to compare.",
        step_1: "The first step is to convert our denominator of 20 to 100 to represent 100% which is in percent form.",
        step_2: "Next we need to get our multiplier to convert the numerator. We do this by dividing 100 by our denominator (20). 100 divided by 20 is 5 which is our multiplier.",
        step_3: "vLastly, we convert our numerator (5) using the same multipler we just calculated (5) to get our percentage."
    },

    {
        claimed: true,
        winner: 'https://opensea.io/JoshuAntona',
        winner_name: 'JoshuAntona',
        open_sea_url: "https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/45467654088607569510196568564608339478309866350944487180964186462126195343361",
        question: 'What are the factors of 33',
        slug:'what-are-the-factors-of-33',
        type_of_question: 'factorization',
        meta_description: "What are the factors of 33? Solve this problem and earn a money reward. Learn how to find the factors of 33 by creating a list of the factors and using the prime factors method.",
        page_thumbnail: "gold-chest.webp",
        answer_tip: "",
        hints_intro: "Hints to help you find the factors of 33",
        hint_1_title: "Start with the smallest factors:",
        hint_1: "Begin by dividing the number by the smallest prime numbers. This way, you can quickly identify which numbers are not factors and move on to the next number.",
        hint_2_title: "Divide and conquer:",
        hint_2: "Keep dividing the number by different numbers to see if they are factors. Once you find a factor, divide the number by that factor again to see if it is a prime factor.",
        hint_3_title: "Factor out common factors:",
        hint_3: "If you have a sum or a product of numbers, look for common factors that you can factor out.",
        step_intro: "To factorize the number 33, we are going to find all the numbers that multiply together to make 33. These numbers are called factors of 33.",
        step_1: "We can start by dividing 33 by 1 and see if it goes evenly. To divide, we can use the symbol ÷. When we divide 33 by 1, we get 33 with no remainder. So 1 is a factor of 33.",
        step_2: "Now we will move on to the number 2, and see if it divides evenly into 33. When we divide 33 by 2, we get 16 with a remainder of 1. So 2 is not a factor of 33.",
        step_3: "You should be getting the hang of it right now! See if you can complete the rest of the factors of 33. When you feel like you are complete, head up back to the top of the page and submit your answer."
    },

    {
        question: 'What are the factors of 100',
        slug:'what-are-the-factors-of-100',
        type_of_question: 'factorization',
        meta_description: "What are the factors of 100? Learn how to find the factors of 100 using prime factors. Earn a money reward if you can solve this question correctly!",
        page_thumbnail: "2.webp",
        answer_tip: "",
        hints_intro: "Factoring numbers is like taking apart a puzzle to find the smaller parts that make up the bigger number. Here's how you can do it:",
        hint_1_title: "Divide the number:",
        hint_1: "Start with the smallest number, which is 1, and see if the bigger number can be divided by it. If it can, write it down as a factor. Then move on to the next number and keep dividing until you can't divide anymore.",
        hint_2_title: "Look for common factors:",
        hint_2: "If you have a sum or a product of numbers, look for parts that are the same and divide them out. This makes it easier to find the rest of the factors.",
        hint_3_title: "Use a factor tree:",
        hint_3: "A factor tree is a diagram that helps you organize the factors of a number. Start with the big number and divide it by the smallest prime factor. Then divide each of the smaller numbers until you reach a prime factor. Prime factors are the building blocks of the big number and are unique to it.",
        step_intro: "We are going to go through the first few steps of finding the factors of 100. To factorize the number 100, we first need to understand what it means to break a number down into smaller parts. Think of it like taking apart a puzzle. This is mean to be a guide but not give you the final answer! The first step in breaking down 100 is to find two numbers that multiply together to make 100. These two numbers are called factors of 100.",
        step_1: "One way to find the factors of 100 is to start with the number 1 and see if it divides evenly into 100. To divide, we can use the symbol ÷. When we divide 100 by 1, we get 100 with no remainder. So 1 is a factor of 100.",
        step_2: "Now we will move on to the number 2 and see if it divides evenly into 100. When we divide 100 by 2, we get 50 with no remainder. So 2 is a factor of 100.",
        step_3: "You should be getting the hang of it right now! See if you can complete the rest of the factors of 100. When you feel like you are complete, head up back to the top of the page and submit your answer."
    },

    {
        question: 'What decimal is 1/6',
        slug:'what-decimal-is-1:6',
        type_of_question: 'decimal',
        meta_description: "What decimal is 1/6? Learn how to convert 1/6 into a decimal and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "3.webp",
        answer_tip: "Limit your answer to four decimal places, for example 0.3333",
        hints_intro: "Factoring numbers is like taking apart a puzzle to find the smaller parts that make up the bigger number. Here's how you can do it:",
        hint_1_title: "Divide the numerator by the denominator:",
        hint_1: "To convert a fraction into a decimal, simply divide the numerator by the denominator. This gives you the value of the fraction as a decimal.",
        hint_2_title: "Write down the decimal places:",
        hint_2: "When dividing the numerator by the denominator, keep writing down the decimal places until you get a repeating pattern or the division terminates (reaches a finite answer).",
        hint_3_title: "Use a calculator:",
        hint_3: "If you're having trouble dividing the numerator by the denominator, you can use a calculator to do it for you. Just be sure to keep track of the decimal places, as you may need to round the answer to the appropriate number of decimal places.",
        step_intro: "A decimal is a way to represent numbers that are not whole numbers, such as fractions or parts of a whole. Decimals use a decimal point to show the value of the fraction in relation to a whole.",
        step_1: "To convert 1/6 into a decimal, we need to divide the numerator (1) by the denominator (6).",
        step_2: "To divide 1 by 6, we start by writing 0.1 as the first digit after the decimal point. This is because 10 divided by 6 equals 1 with a remainder of 4.",
        step_3: "Next, we multiply 6 by the first digit after the decimal point (0.1) to see what the next digit will be. 6 x 0.1 = 0.6. Now we write the second digit after the decimal point (0.6) and our decimal is 0.16 so far."
    },

    {
        question: 'What decimal is 5/6',
        slug:'what-decimal-is-5:6',
        type_of_question: 'decimal',
        meta_description: "What decimal is 5/6? Learn how to convert 5/6 into a decimal and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "2.webp",
        answer_tip: "Limit your answer to four decimal places, for example 0.1111",
        hints_intro: "Here are some hints and tips to help convert fractions into decimals:",
        hint_1_title: "Divide the numerator by the denominator:",
        hint_1: "To convert a fraction into a decimal, simply divide the numerator by the denominator. This gives you the value of the fraction as a decimal.",
        hint_2_title: "Write down the decimal places:",
        hint_2: "When dividing the numerator by the denominator, keep writing down the decimal places until you get a repeating pattern or the division terminates.",
        hint_3_title: "Use a calculator:",
        hint_3: "If you're having trouble dividing the numerator by the denominator, you can use a calculator to do it for you. Just be sure to keep track of the decimal places, as you may need to round the answer to the appropriate number of decimal places.",
        step_intro: "A decimal is a way to represent numbers that are not whole numbers, such as fractions or parts of a whole. Decimals use a decimal point to show the value of the fraction in relation to a whole.",
        step_1: "To convert 5/6 into a decimal, we need to divide the numerator (5) by the denominator (6).",
        step_2: "To divide 5 by 6, we start by writing 8 as the first digit after the decimal point.",
        step_3: "Our final answer is 0.83333..., with the 3s repeating forever. This is the decimal representation of 5/6."
    },

    {
        question: 'What percentage of 8 is 5',
        slug:'what-percentage-of-8-is-5',
        type_of_question: 'percentage',
        meta_description: "What percentage of 8 is 5? Use equivalent fractions to convert 8 to a percent of 5 and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "4.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to help convert 8 into 5 as a percent:",
        hint_1_title: "Divide the numerator (the top number) of the fraction by the denominator (the bottom number)",
        hint_1: "To convert a percent into a fraction, we need to convert to an equivalent fraction with denominator 100.",
        hint_2_title: "Multiply the answer from step 1 by 100:",
        hint_2: "Convert the fraction to a decimal first, then multiply the answer by 100",
        hint_3_title: "Use a calculator:",
        hint_3: "If you're having trouble dividing the numerator by the denominator, you can use a calculator to do it for you.",
        step_intro: "Percentage is a way of expressing a number as a part of 100. To find the percentage of a number, we first need to divide it by the total amount and then multiply by 100.",
        step_1: "First we need to convert our denominator 8 to 100 to represent 100% as a percent.",
        step_2: "Next we divide 100 by our denominator (8) to work out the multiplier. 100 divided by 8 is 12.5 which is our multiplier.",
        step_3: "Our last step is then to convert our numerator (5) using the same multipler (12.5) to get our percentage."
    },

    {
        question: 'What percentage of 20 is 5',
        slug:'what-percentage-of-20-is-5',
        type_of_question: 'percentage',
        meta_description: "What percentage of 20 is 5? Learn how to calculate what percent 20 is of 5 and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "1.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to help convert 5 into 20 as a percent:",
        hint_1_title: "Use equivalent fractions by identifying the numerator and denominator.",
        hint_1: "To convert a percent into a fraction, we need to convert to an equivalent fraction with denominator 100.",
        hint_2_title: "Convert to a percentage by multiplying 100:",
        hint_2: "Convert the fraction to a decimal first, then multiply the answer by 100",
        hint_3_title: "Use a calculator:",
        hint_3: "If you're having trouble dividing the numerator by the denominator, you can use a calculator to do it for you. Ideally use a calculate to check your answer as it is better to practice converting fractions to percentages and using a calculator to check your answer.",
        step_intro: "Percentage is a way of expressing a number as a part of 100. To find the percentage of a number, we first need to divide it by the total amount and then multiply by 100.",
        step_1: "First we need to convert our denominator 20 to 100 to represent 100% as a percent.",
        step_2: "Next we divide 100 by our denominator (20) to work out the multiplier. 100 divided by 20 is 5 which is our multiplier.",
        step_3: "Our last step is then to convert our numerator (5) using the same multipler (5) to get our percentage."
    },

    {
        question: '1.5 as a fraction',
        slug:'1.5-as-a-fraction',
        type_of_question: 'fraction',
        meta_description: "What is 1.5 as a fraction? Learn how to solve 1.5 as a fraction and earn a money reward if you can solve the question correctly.",
        page_thumbnail: "4.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to help solve 1.5 as a fraction:",
        hint_1_title: "Understand what a fraction means:",
        hint_1: "A fraction represents a part of a whole. If you have a pie and you cut it into eight equal slices, each slice is 1/8 of the whole pie.",
        hint_2_title: "Convert the decimal to a fraction:",
        hint_2: "To convert 1.5 to a fraction, we need to understand that the decimal point separates the whole number from the decimal part. In this case, 1 is the whole number and 0.5 is the decimal part. ",
        hint_3_title: "Simplify:",
        hint_3: " To convert the decimal part to a fraction, we can write 0.5 as 5/10. We can simplify this fraction by dividing both the numerator and denominator by 5, which gives us 1/2.",
        step_intro: "We need to understand how to convert decimals into fractions to solve 1.5 as a fraction.",
        step_1: "The first step is to write 1.5 as a fraction with a denominator of 1. So, 0.5 becomes 50/100.",
        step_2: "Then the next step is to identify the place value. In this case, we can see that the decimal point is after the hundredth place. This means that the denominator of the fraction will be 100.",
        step_3: "Lastly you will multiply the decimal by the denominator. Take 0.50 and multiply by 100 to get the numerator of the fraction. So, 50/100 is your fraction. Lastly simplify this fraction by dividing by the greatest common factor (which is 50) to get the fraction in its simplist form."
    },

    {
        question: 'Factors of 75',
        slug:'factors-of-75',
        type_of_question: 'factorization',
        meta_description: "What are the factors of 75? Learn how to determine the factors of 75 and earn a money reward if you can solve this question correctly.",
        page_thumbnail: "2.webp",
        answer_tip: "",
        hints_intro: "Here are some hints and tips to find the factors of 75:",
        hint_1_title: "Understand what factors mean:",
        hint_1: "Factors are numbers that can be multiplied together to get a particular number. For example, the factors of 6 are 1, 2, 3, and 6 because 1 x 6 = 6 and 2 x 3 = 6.",
        hint_2_title: "Break down the number:",
        hint_2: "To find the factors of 75, it can be helpful to break it down into its prime factors. Prime factors are numbers that are only divisible by 1 and themselves. In this case, 75 can be broken down into 3 x 5 x 5.",
        hint_3_title: "Find the factors:",
        hint_3: "To find the factors of 75, we can start by listing all the factors of 3, 5, and 5. The factors of 3 are 1 and 3. The factors of 5 are 1 and 5. We can list the factors by multiplying these together: 1 x 1 x 1 = 1, 1 x 1 x 5 = 5, 1 x 5 x 1 = 5, 1 x 5 x 5 = 25, 3 x 1 x 1 = 3, 3 x 1 x 5 = 15, 3 x 5 x 1 = 15, and 3 x 5 x 5 = 75.",
        step_intro: "To find the factors of the number 75, we need to find numbers that multiply together to make 33.",
        step_1: "The easiest is to start by dividing 75 by 1 and see if it goes evenly. To divide, we can use the symbol ÷. When we divide 75 by 1, we get 75 with no remainder which tells us 1 and 75 are factors.",
        step_2: "Now we will move on to the number 2, and see if it divides evenly into 75. When we divide 75 by 2, we end up with a remainder of 5 so we know that 2 is not a factor.",
        step_3: "You should be getting the hang of it right now! Keep going down the list in the same way as step 1 and 2 then submit your answer in the space above!"
    },
  ];
  